export interface VaNumber {
    bank: 'permata' | 'bni' | 'bri' | 'bca'; // Name of the bank that processes bank transfer transaction. String(255) Required
    va_number: string; // Virtual account number generated by Midtrans. String(255) Required
  }
  
  export type VaNumbers = VaNumber[]; // Array of Virtual Account Number. JSON Array Required